name: release

on:
  release:
    types:
      - created

jobs:
  release:
    name: release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: DotnetVersion
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack RoushTech.APRSsharp.AprsParser
        run: dotnet pack src/AprsParser/AprsParser.csproj --configuration Release --no-build

      - name: Pack RoushTech.APRSsharp.AprsIsClient
        run: dotnet pack src/AprsIsClient/AprsIsClient.csproj --configuration Release --no-build

      - name: Pack RoushTech.APRSsharp.KissTnc
        run: dotnet pack src/KissTnc/KissTnc.csproj --configuration Release --no-build

      - name: Pack RoushTech.APRSsharp.Shared
        run: dotnet pack src/Shared/Shared.csproj --configuration Release --no-build

      - name: Publish RoushTech.APRSsharp.AprsParser
        run: dotnet nuget push src/AprsParser/bin/Release/RoushTech.APRSsharp.AprsParser.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish RoushTech.APRSsharp.AprsIsClient
        run: dotnet nuget push src/AprsIsClient/bin/Release/RoushTech.APRSsharp.AprsIsClient.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish RoushTech.APRSsharp.KissTnc
        run: dotnet nuget push src/KissTnc/bin/Release/RoushTech.APRSsharp.KissTnc.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish RoushTech.APRSsharp.Shared
        run: dotnet nuget push src/Shared/bin/Release/RoushTech.APRSsharp.Shared.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
